const SEARCH_INDEX=(function(){var idx=[];(typeof allReviews!=='undefined'?allReviews:[]).forEach(function(d){idx.push({title:d.title,url:d.url,type:'Movie'});});(typeof allComics!=='undefined'?allComics:[]).forEach(function(d){idx.push({title:d.title,url:d.url,type:'Comic'});});(typeof allGames!=='undefined'?allGames:[]).forEach(function(d){idx.push({title:d.title,url:d.url,type:'Game'});});(typeof allArticles!=='undefined'?allArticles:[]).forEach(function(d){idx.push({title:d.title,url:d.url,type:d.type==='Ranking'?'Ranking':'Article'});});return idx;})();const POPULAR_SEARCHES=['The Dark Knight','Watchmen','Hades','Parasite','Baahubali'];document.addEventListener('DOMContentLoaded',function(){const mainEl=document.querySelector('main');if(mainEl){if(!mainEl.id)mainEl.id='main-content';const skip=document.createElement('a');skip.href='#main-content';skip.className='skip-link';skip.textContent='Skip to main content';document.body.insertBefore(skip,document.body.firstChild);}
const path=window.location.pathname;document.querySelectorAll('.subheader a').forEach(function(a){const href=a.getAttribute('href');if(href&&(path.endsWith(href)||(href.includes('reviews')&&path.includes('/Reviews/'))||(href.includes('games')&&path.includes('/Games/'))||(href.includes('comics')&&path.includes('/Comic/'))||(href.includes('articles')&&path.includes('/Articles/')))){a.classList.add('active');}});(function(){const navEl=document.querySelector('.subheader');if(!navEl)return;const sample=navEl.querySelector('a[href*="index.html"]');const prefix=sample?sample.getAttribute('href').replace('index.html',''):'';const searchWrap=document.createElement('div');searchWrap.className='rt-search';searchWrap.innerHTML='<button type="button" class="rt-search-toggle" aria-label="Search reviews" aria-expanded="false" aria-controls="rt-search-panel">🔍</button>'+
'<div class="rt-search-panel" id="rt-search-panel" hidden>'+
'<input type="search" class="rt-search-input" placeholder="Search reviews and articles…" aria-label="Search Reel Talk" role="combobox" aria-expanded="false" aria-autocomplete="list" aria-controls="rt-search-results" autocomplete="off">'+
'<div class="rt-search-results" id="rt-search-results" role="listbox"></div>'+
'</div>';navEl.appendChild(searchWrap);const toggle=searchWrap.querySelector('.rt-search-toggle');const panel=searchWrap.querySelector('.rt-search-panel');const input=searchWrap.querySelector('.rt-search-input');const results=searchWrap.querySelector('.rt-search-results');function escapeHtml(s){return String(s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
let activeIndex=-1;function setActive(i){const opts=results.querySelectorAll('.rt-search-result');opts.forEach(function(o){o.classList.remove('is-active');});activeIndex=i;if(i>=0&&opts[i]){opts[i].classList.add('is-active');opts[i].scrollIntoView({block:'nearest'});input.setAttribute('aria-activedescendant',opts[i].id);}else{input.removeAttribute('aria-activedescendant');}}
function renderResults(items,heading){activeIndex=-1;if(!items.length){results.innerHTML='<p class="rt-search-empty">No matches - try another title.</p>';return;}
results.innerHTML=(heading?'<p class="rt-search-heading">'+escapeHtml(heading)+'</p>':'')+
items.map(function(it,i){return'<a class="rt-search-result" id="rt-search-opt-'+i+'" role="option" href="'+prefix+encodeURI(it.url)+'"><span class="rt-search-result-type">'+escapeHtml(it.type)+'</span>'+escapeHtml(it.title)+'</a>';}).join('');}
function showDefault(){let recent=[];try{recent=JSON.parse(localStorage.getItem('rt_recently_viewed')||'[]');}catch(e){recent=[];}
if(recent.length){renderResults(recent.slice(0,5).map(function(r){return{title:r.title,url:r.url,type:'Recently Viewed'};}),'Recently Viewed');}else{renderResults(POPULAR_SEARCHES.map(function(q){const match=SEARCH_INDEX.find(function(it){return it.title.indexOf(q)!==-1;});return match||{title:q,url:'',type:'Popular'};}).filter(function(it){return it.url;}),'Popular Searches');}}
function openPanel(){panel.removeAttribute('hidden');toggle.setAttribute('aria-expanded','true');input.setAttribute('aria-expanded','true');showDefault();input.focus();}
function closePanel(focusToggle){panel.setAttribute('hidden','');toggle.setAttribute('aria-expanded','false');input.setAttribute('aria-expanded','false');if(focusToggle)toggle.focus();}
toggle.addEventListener('click',function(){const isOpen=panel.hasAttribute('hidden')===false;if(isOpen){closePanel(false);}else{openPanel();}});input.addEventListener('input',function(){const q=input.value.trim().toLowerCase();if(!q){showDefault();return;}
const matches=SEARCH_INDEX.filter(function(it){return it.title.toLowerCase().indexOf(q)!==-1;}).slice(0,8);renderResults(matches,null);});input.addEventListener('keydown',function(e){const opts=results.querySelectorAll('.rt-search-result');if(e.key==='ArrowDown'){e.preventDefault();if(!opts.length)return;setActive(activeIndex<opts.length-1?activeIndex+1:0);}else if(e.key==='ArrowUp'){e.preventDefault();if(!opts.length)return;setActive(activeIndex>0?activeIndex-1:opts.length-1);}else if(e.key==='Enter'){if(activeIndex>=0&&opts[activeIndex]){e.preventDefault();window.location.href=opts[activeIndex].getAttribute('href');}}});document.addEventListener('click',function(e){if(!searchWrap.contains(e.target)){closePanel(false);}});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!panel.hasAttribute('hidden')){closePanel(true);}});})();const nav=document.querySelector('.subheader');if(nav){const btn=document.createElement('button');btn.className='nav-toggle';btn.setAttribute('aria-label','Toggle navigation');btn.setAttribute('aria-expanded','false');btn.innerHTML='<span></span><span></span><span></span>';nav.prepend(btn);btn.addEventListener('click',function(){const isOpen=nav.classList.toggle('nav-open');btn.setAttribute('aria-expanded',isOpen);});document.addEventListener('click',function(e){if(!nav.contains(e.target)){nav.classList.remove('nav-open');btn.setAttribute('aria-expanded','false');}});}
function toggleTheme(){const isDark=document.documentElement.getAttribute('data-theme')==='dark';if(isDark){document.documentElement.removeAttribute('data-theme');localStorage.setItem('theme','light');}else{document.documentElement.setAttribute('data-theme','dark');localStorage.setItem('theme','dark');}}
function makeSwitch(extraClass){const sw=document.createElement('button');sw.className='dark-switch '+extraClass;sw.setAttribute('aria-label','Toggle dark mode');sw.innerHTML=`<span class="dark-switch-label">Dark mode</span><span class="dark-switch-track"><span class="dark-switch-thumb"></span></span>`;sw.addEventListener('click',toggleTheme);return sw;}
const headerEl=document.querySelector('header');if(headerEl){headerEl.appendChild(makeSwitch('dark-switch-desktop'));}
if(nav)nav.appendChild(makeSwitch('dark-switch-mobile'));const topBtn=document.createElement('button');topBtn.className='back-to-top';topBtn.setAttribute('aria-label','Back to top');topBtn.textContent='↑';document.body.appendChild(topBtn);window.addEventListener('scroll',function(){topBtn.classList.toggle('visible',window.scrollY>300);},{passive:true});topBtn.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'});});const footerMount=document.getElementById('rt-footer-mount');if(footerMount){footerMount.outerHTML='<section class="newsletter-section" id="newsletter"><div class="newsletter-inner"><h2 class="newsletter-heading">Stay in the Loop</h2><p class="newsletter-desc">New reviews and articles - all in one place, not one at a time. No spam, unsubscribe anytime.</p><form class="newsletter-form" id="newsletter-form"><input type="email" class="newsletter-input" id="newsletter-email" placeholder="your@email.com" aria-label="Email address" required><button type="submit" class="newsletter-btn" id="newsletter-btn">Subscribe</button></form><p class="newsletter-note" id="newsletter-note">Powered by Beehiiv</p></div></section><footer class="site-footer"><p class="footer-text">Find more of my work:</p><ul class="footer-links"><li>&#127916; <a href="https://boxd.it/4HvP3">Letterboxd</a></li><li>&#128247; <a href="https://www.instagram.com/reeltalk_hub">Instagram</a></li><li>&#128231; <a href="#newsletter">Newsletter</a></li></ul></footer>';}});