// ─── ADD NEW REVIEWS HERE ──────────────────────────────────────────────────
// Add the newest review at the TOP of the array.
// After adding, also update the preload href in index.html line ~11:
//   <link rel="preload" as="image" href="...your new reviewImage path...">
// That one change keeps PageSpeed LCP fast.
// ───────────────────────────────────────────────────────────────────────────

const allReviews = [
    {
        title:       'American Psycho (2000)',
        desc:        'A comedy about a void wearing a suit. And nobody notices.',
        poster:      'Images/Review/Poster/american psycho poster.webp',
        reviewImage: 'Images/Review/Review/american psycho review image.webp',
        url:         'Reviews/american-psycho.html',
        date:        '2026-05-25',
        type:        'Movie Review',
    },
    {
        title:       'Baahubali: The Beginning (2015)',
        desc:        'Epic in scale, uneven on the ground. But when it commits, nothing else in Indian cinema matches it.',
        poster:      'Images/Review/Poster/baahubali poster.webp',
        reviewImage: 'Images/Review/Review/baahubali review image.webp',
        url:         'Reviews/baahubali.html',
        date:        '2026-06-10',
        type:        'Movie Review',
    },
    {
        title:       'Casablanca (1942)',
        desc:        'Eighty years have not touched it.',
        poster:      'Images/Review/Poster/casablanca poster.webp',
        reviewImage: 'Images/Review/Review/casablanca review image.webp',
        url:         'Reviews/casablanca.html',
        date:        '2026-05-18',
        type:        'Movie Review',
    },
    {
        title:       'Drive (2011)',
        desc:        'The craft is precise. The distance is real. Whether that is a flaw depends on what you came for.',
        poster:      'Images/Review/Poster/drive poster.webp',
        reviewImage: 'Images/Review/Review/drive review image.webp',
        url:         'Reviews/drive.html',
        date:        '2026-05-27',
        type:        'Movie Review',
    },
    {
        title:       'Fight Club (1999)',
        desc:        'A diagnosis, not a celebration. One of the most precisely constructed films of the nineties.',
        poster:      'Images/Review/Poster/fight club poster.webp',
        reviewImage: 'Images/Review/Review/fight club review image.webp',
        url:         'Reviews/fight-club.html',
        date:        '2026-05-04',
        type:        'Movie Review',
    },
    {
        title:       'Godzilla (1954)',
        desc:        'Could have been pulp. Instead it is a film about fear, responsibility, and things you cannot un-create.',
        poster:      'Images/Review/Poster/godzilla poster.webp',
        reviewImage: 'Images/Review/Review/godzilla review image.webp',
        url:         'Reviews/godzilla.html',
        date:        '2026-06-03',
        type:        'Movie Review',
    },
    {
        title:       'Parasite (2019)',
        desc:        'The most precisely constructed film of the last decade. A comedy, thriller, critique, and tragedy all at once.',
        poster:      'Images/Review/Poster/parasite poster.webp',
        reviewImage: 'Images/Review/Review/parasite review image.webp',
        url:         'Reviews/parasite.html',
        date:        '2026-04-27',
        type:        'Movie Review',
    },
    {
        title:       'Spirited Away (2001)',
        desc:        'Some films are made for children. This one is made for anyone who was ever a child.',
        poster:      'Images/Review/Poster/spirited away poster.webp',
        reviewImage: 'Images/Review/Review/spirited away review image.webp',
        url:         'Reviews/spirited-away.html',
        date:        '2026-05-11',
        type:        'Movie Review',
    },
    {
        title:       'The Dark Knight (2008)',
        desc:        'A near-perfect crime thriller that changed what superhero films were allowed to be — for better and for worse.',
        poster:      'Images/Review/Poster/dark knight poster.webp',
        reviewImage: 'Images/Review/Review/dark knight review image.webp',
        url:         'Reviews/dark-knight.html',
        date:        '2026-04-15',
        type:        'Movie Review',
    },
    {
        title:       'The Amazing Spider-Man (2012)',
        desc:        'Andrew Garfield takes on the iconic role in this grounded reboot of the Spider-Man story.',
        poster:      'Images/Review/Poster/tasm poster.jpg',
        reviewImage: 'Images/Review/Review/tasm review.webp',
        url:         'Reviews/tasm.html',
        date:        '2025-03-01',
        type:        'Movie Review',
    },
    {
        title:       'Batman v. Superman: Dawn of Justice (2016)',
        desc:        'The two most iconic DC heroes clash in a dark and divisive battle of ideals.',
        poster:      'Images/Review/Poster/bvs poster.jpg',
        reviewImage: 'Images/Review/Review/bvs review image.webp',
        url:         'Reviews/bvs.html',
        date:        '2025-02-15',
        type:        'Movie Review',
    },
    {
        title:       'Spider-Man 3 (2007)',
        desc:        'Peter Parker faces his darkest chapter as multiple villains and personal demons collide.',
        poster:      'Images/Review/Poster/sm3 poster.webp',
        reviewImage: 'Images/Review/Review/sm3 review .webp',
        url:         'Reviews/sm3.html',
        date:        '2025-02-01',
        type:        'Movie Review',
    },
    {
        title:       'Spider-Man 2 (2004)',
        desc:        'A modern blueprint for superhero storytelling that balances spectacle with genuine heart.',
        poster:      'Images/Review/Poster/sm2 poster.jpg',
        reviewImage: 'Images/Review/Review/sm2 review .webp',
        url:         'Reviews/sm2.html',
        date:        '2025-01-15',
        type:        'Movie Review',
    },
    {
        title:       '500 Days of Summer (2009)',
        desc:        'A refreshingly honest look at love that refuses to follow the usual romantic playbook.',
        poster:      'Images/Review/Poster/500dos poster.png',
        reviewImage: 'Images/Review/Review/500 dos review.webp',
        url:         'Reviews/500dos.html',
        date:        '2025-01-01',
        type:        'Movie Review',
    },
    {
        title:       'Star Wars: Episode III — Revenge of the Sith (2005)',
        desc:        "Anakin Skywalker's tragic fall to the dark side brings the prequel trilogy to a powerful close.",
        poster:      'Images/Review/Poster/sw3 poster.jpg',
        reviewImage: 'Images/Review/Review/sw3 review image.avif',
        url:         'Reviews/sw3.html',
        date:        '2024-12-15',
        type:        'Movie Review',
    },
    {
        title:       'Superman (2025)',
        desc:        "James Gunn's take on the Man of Steel brings a fresh, hopeful energy to the DC universe.",
        poster:      'Images/Review/Poster/superman poster.jpg',
        reviewImage: 'Images/Review/Review/superman review image.webp',
        url:         'Reviews/superman.html',
        date:        '2024-12-01',
        type:        'Movie Review',
    },
    {
        title:       'Kalki 2898 AD (2024)',
        desc:        'An ambitious sci-fi epic that blends Hindu mythology with a sprawling dystopian future.',
        poster:      'Images/Review/Poster/kalki poster.jpg',
        reviewImage: 'Images/Review/Review/kalki review image.webp',
        url:         'Reviews/kalki.html',
        date:        '2024-11-15',
        type:        'Movie Review',
    },
    {
        title:       'Spider-Man (2002)',
        desc:        "Sam Raimi's origin story set the template for modern superhero cinema.",
        poster:      'Images/Review/Poster/spider-man poster.jpg',
        reviewImage: 'Images/Review/Review/spider-man review image.webp',
        url:         'Reviews/spider-man.html',
        date:        '2024-11-01',
        type:        'Movie Review',
    },
    {
        title:       'Transformers (2007)',
        desc:        "Michael Bay's blockbuster debut for the Autobots delivers non-stop spectacle.",
        poster:      'Images/Review/Poster/Transformers (2007).png',
        reviewImage: 'Images/Review/Review/transformers review image.webp',
        url:         'Reviews/transformers.html',
        date:        '2024-10-15',
        type:        'Movie Review',
    },
    {
        title:       'Man of Steel (2013)',
        desc:        "Zack Snyder reimagines Superman's origin as a brooding, visually striking sci-fi epic.",
        poster:      'Images/Review/Poster/mos_poster.jpeg',
        reviewImage: 'Images/Review/Review/mos review image.webp',
        url:         'Reviews/mos.html',
        date:        '2024-10-01',
        type:        'Movie Review',
    },
];
